platform :ios, '8.0'

target 'swiftDemo' do
  use_frameworks!

  pod "Alamofire"
  pod "AFNetworking"
  pod "SDWebImage"
  pod "YYModel"
  pod "FMDB"
  pod "SVProgressHUD"
  pod "pop"
  pod "SnapKit"

end
